# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_lite.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5.QtWidgets import *
import sqlite3

class AddUserDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Добавить пользователя")
        
        layout = QFormLayout(self)
        
        self.name_edit = QLineEdit()
        self.email_edit = QLineEdit()
        self.age_edit = QLineEdit()
        
        layout.addRow("Имя:", self.name_edit)
        layout.addRow("Email:", self.email_edit)
        layout.addRow("Возраст:", self.age_edit)
        
        # Кнопки ОК/Отмена
        self.button_box = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)
        layout.addRow(self.button_box)
    
    def get_data(self):
        return (self.name_edit.text(), self.email_edit.text(), self.age_edit.text())



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 620)  # чуть увеличил высоту, чтобы было удобнее
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Таблица
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 1011, 500))  # уменьшил высоту, чтобы освободить место
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        
        # Панель справа
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1030, 10, 241, 500))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        
        # Поля ввода под таблицей
        self.lineEdit_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_1.setGeometry(QtCore.QRect(10, 520, 240, 30))
        self.lineEdit_1.setPlaceholderText("Поле 1")
        
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 520, 240, 30))
        self.lineEdit_2.setPlaceholderText("Поле 2")
        
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(510, 520, 240, 30))
        self.lineEdit_3.setPlaceholderText("Поле 3")
        
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(760, 520, 240, 30))
        self.lineEdit_4.setPlaceholderText("Поле 4")
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        # Меню
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addSeparator()
        self.menu.addAction(self.action_4)
        self.menu_2.addAction(self.action_5)
        self.menu_2.addAction(self.action_6)
        self.menu_2.addAction(self.action_7)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        
        # автоматическое обновление таблицы (если метод определён)
        self.refresh_table()
        
        # подключение кнопок
        self.pushButton.clicked.connect(self.addData)
        self.pushButton_2.clicked.connect(self.editData)
        self.pushButton_3.clicked.connect(self.deleteData)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Редактор баз данных SQLITE"))
        self.pushButton.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_2.setText(_translate("MainWindow", "Изменить"))
        self.pushButton_3.setText(_translate("MainWindow", "Удалить"))
        self.action.setText(_translate("MainWindow", "О программе"))
        self.action_2.setText(_translate("MainWindow", "Об авторе"))
        self.action_4.setText(_translate("MainWindow", "Выход"))
        self.action_5.setText(_translate("MainWindow", "Добавить"))
        self.action_6.setText(_translate("MainWindow", "Изменить"))
        self.action_7.setText(_translate("MainWindow", "Удалить"))


    def refresh_table(self):
        conn = sqlite3.connect('my_database.db')
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM Users")
        rows = cursor.fetchall()
              
        self.tableWidget.setRowCount(len(rows))
        self.tableWidget.setColumnCount(len(rows[0]))
        for i, row in enumerate(rows):
            for j, value in enumerate(row):
                self.tableWidget.setItem(i, j, QTableWidgetItem(str(value)))

        conn.close()  

    def addData(self):
        conn = sqlite3.connect('my_database.db')
        cursor = conn.cursor()
        try:
            cursor.execute('INSERT INTO Users VALUES (?,?,?,?)', (self.lineEdit_1.text(),self.lineEdit_2.text(),self.lineEdit_3.text(),self.lineEdit_4.text()))
            conn.commit()
        except sqlite3.Error as e:
            print(e)
        finally:
            self.refresh_table()
            conn.close()

    def editData(self):
        conn = sqlite3.connect('my_database.db')
        cursor = conn.cursor()
        current_row = self.tableWidget.currentRow()
        id_item = self.tableWidget.item(current_row, 0)
        old_id = int(id_item.text())
        new_id = int(self.lineEdit_1.text())
        name = self.lineEdit_2.text()
        email = self.lineEdit_3.text()
        age = int(self.lineEdit_4.text())
        try:
            cursor.execute(
                "UPDATE Users SET id=?, username=?, email=?, age=? WHERE id=?",
                (new_id, name, email, age, old_id)
            )
            conn.commit()
        except sqlite3.Error as e:
            print(e)
        finally:
            self.refresh_table()
            conn.close()

    def deleteData(self):
        conn = sqlite3.connect('my_database.db')
        cursor = conn.cursor()
        current_row = self.tableWidget.currentRow()
        id_item = int(self.tableWidget.item(current_row, 0).text())
        try:
            cursor.execute('DELETE FROM Users WHERE id=?', (id_item,))
            conn.commit()
        except sqlite3.Error as e:
            print(e)
        finally:
            self.refresh_table()
            conn.close()
        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
